package handler

import (
	"encoding/json"
	"fmt"
	"net/http"
	"testing"
	"time"

	"github.com/Mininglamp-OSS/octo-smart-summary/internal/middleware"
	"github.com/Mininglamp-OSS/octo-smart-summary/internal/model"
	"github.com/gin-gonic/gin"
	"gorm.io/gorm"
)

func setupRound13TaskRouter(h *TaskHandler) *gin.Engine {
	gin.SetMode(gin.TestMode)
	r := gin.New()
	r.Use(middleware.AuthMiddleware(&mockTokenResolver{}), middleware.SpaceMiddleware())
	r.GET("/api/v1/summaries", h.ListSummaries)
	r.GET("/api/v1/summaries/:id", h.GetSummary)
	r.GET("/api/v1/summaries/:id/result", h.GetResult)
	return r
}

func decodeRound13Response(t *testing.T, body []byte) map[string]interface{} {
	t.Helper()
	var resp map[string]interface{}
	if err := json.Unmarshal(body, &resp); err != nil {
		t.Fatalf("unmarshal response: %v\nbody=%s", err, string(body))
	}
	return resp
}

func seedRound13DisplayResultTask(t *testing.T, db *gorm.DB) (int64, time.Time, time.Time) {
	t.Helper()
	now := time.Now().UTC()
	editedAt := now.Add(-30 * time.Minute).UTC().Truncate(time.Second)
	editedGeneratedAt := now.Add(-time.Hour).UTC().Truncate(time.Second)
	autoGeneratedAt := now.UTC().Truncate(time.Second)

	task := model.SummaryTask{
		TaskNo:         "TST-R13-DISPLAY",
		SpaceID:        "space1",
		CreatorID:      "creator1",
		Title:          "display result",
		SummaryMode:    model.ModeByPerson,
		Status:         model.StatusCompleted,
		TimeRangeStart: now.Add(-24 * time.Hour),
		TimeRangeEnd:   now,
	}
	if err := db.Create(&task).Error; err != nil {
		t.Fatalf("create task: %v", err)
	}
	if err := db.Create(&model.SummarySource{TaskID: task.ID, SourceType: model.SourceGroup, SourceID: "grp-r13", SourceName: "group"}).Error; err != nil {
		t.Fatalf("create source: %v", err)
	}
	if err := db.Create(&model.SummaryParticipant{TaskID: task.ID, UserID: "creator1", UserName: "Creator", Status: model.ParticipantCompleted}).Error; err != nil {
		t.Fatalf("create participant: %v", err)
	}

	edited := model.SummaryResult{
		TaskID:         task.ID,
		Content:        "hand edited summary",
		TotalMsgCount:  42,
		TotalTokenUsed: 111,
		ModelVersion:   "manual-v5",
		Version:        5,
		EditedAt:       &editedAt,
		GeneratedAt:    editedGeneratedAt,
	}
	if err := db.Create(&edited).Error; err != nil {
		t.Fatalf("create edited result: %v", err)
	}
	auto := model.SummaryResult{
		TaskID:         task.ID,
		Content:        "new auto summary",
		TotalMsgCount:  7,
		TotalTokenUsed: 22,
		ModelVersion:   "auto-v6",
		Version:        6,
		GeneratedAt:    autoGeneratedAt,
	}
	if err := db.Create(&auto).Error; err != nil {
		t.Fatalf("create auto result: %v", err)
	}

	return task.ID, editedAt, editedGeneratedAt
}

func TestPR62Round13_DisplayReadPathsPreferEditedResult(t *testing.T) {
	db, imDB := setupTestDBs(t)
	taskID, editedAt, editedGeneratedAt := seedRound13DisplayResultTask(t, db)
	h := NewTaskHandler(db, imDB, "")
	r := setupRound13TaskRouter(h)

	listW := doRequest(r, http.MethodGet, "/api/v1/summaries", "creator1")
	if listW.Code != http.StatusOK {
		t.Fatalf("list status=%d body=%s", listW.Code, listW.Body.String())
	}
	listResp := decodeRound13Response(t, listW.Body.Bytes())
	data := listResp["data"].(map[string]interface{})
	items := data["items"].([]interface{})
	if len(items) != 1 {
		t.Fatalf("list items=%d want 1", len(items))
	}
	item := items[0].(map[string]interface{})
	if int64(item["task_id"].(float64)) != taskID {
		t.Fatalf("list task_id=%v want %d", item["task_id"], taskID)
	}
	if int(item["total_msg_count"].(float64)) != 42 {
		t.Fatalf("list total_msg_count=%v want 42", item["total_msg_count"])
	}
	if item["completed_at"].(string) != editedGeneratedAt.Format(time.RFC3339) {
		t.Fatalf("list completed_at=%v want %s", item["completed_at"], editedGeneratedAt.Format(time.RFC3339))
	}
	if item["result_is_edited"] != true {
		t.Fatalf("list result_is_edited=%v want true", item["result_is_edited"])
	}
	if item["result_edited_at"].(string) != editedAt.Format(time.RFC3339) {
		t.Fatalf("list result_edited_at=%v want %s", item["result_edited_at"], editedAt.Format(time.RFC3339))
	}

	summaryW := doRequest(r, http.MethodGet, fmt.Sprintf("/api/v1/summaries/%d", taskID), "creator1")
	if summaryW.Code != http.StatusOK {
		t.Fatalf("summary status=%d body=%s", summaryW.Code, summaryW.Body.String())
	}
	summaryResp := decodeRound13Response(t, summaryW.Body.Bytes())
	summaryData := summaryResp["data"].(map[string]interface{})
	result := summaryData["result"].(map[string]interface{})
	if result["content"].(string) != "hand edited summary" {
		t.Fatalf("summary content=%q want hand edited summary", result["content"])
	}
	if int(result["version"].(float64)) != 5 {
		t.Fatalf("summary version=%v want 5", result["version"])
	}
	if summaryData["result_is_edited"] != true {
		t.Fatalf("summary result_is_edited=%v want true", summaryData["result_is_edited"])
	}
	if summaryData["result_edited_at"].(string) != editedAt.Format(time.RFC3339) {
		t.Fatalf("summary result_edited_at=%v want %s", summaryData["result_edited_at"], editedAt.Format(time.RFC3339))
	}

	resultW := doRequest(r, http.MethodGet, fmt.Sprintf("/api/v1/summaries/%d/result", taskID), "creator1")
	if resultW.Code != http.StatusOK {
		t.Fatalf("result status=%d body=%s", resultW.Code, resultW.Body.String())
	}
	resultResp := decodeRound13Response(t, resultW.Body.Bytes())
	resultData := resultResp["data"].(map[string]interface{})
	if resultData["content"].(string) != "hand edited summary" {
		t.Fatalf("get result content=%q want hand edited summary", resultData["content"])
	}
	if int(resultData["version"].(float64)) != 5 {
		t.Fatalf("get result version=%v want 5", resultData["version"])
	}
	if resultData["result_is_edited"] != true {
		t.Fatalf("get result result_is_edited=%v want true", resultData["result_is_edited"])
	}
	if resultData["result_edited_at"].(string) != editedAt.Format(time.RFC3339) {
		t.Fatalf("get result result_edited_at=%v want %s", resultData["result_edited_at"], editedAt.Format(time.RFC3339))
	}
}

func TestPR62Round13_GetSummaryKeepsInactiveScheduleBinding(t *testing.T) {
	db, imDB := setupTestDBs(t)
	now := time.Now().UTC()
	nextRun := now.Add(time.Hour)
	sched := model.SummarySchedule{
		SpaceID:       "space1",
		CreatorID:     "creator1",
		Title:         "sched",
		SummaryMode:   model.ModeByPerson,
		IntervalDays:  1,
		RunTime:       "09:00",
		TimeRangeType: 2,
		NextRunAt:     &nextRun,
	}
	if err := db.Create(&sched).Error; err != nil {
		t.Fatalf("create schedule: %v", err)
	}
	if err := db.Model(&sched).Update("is_active", 0).Error; err != nil {
		t.Fatalf("disable schedule: %v", err)
	}
	task := model.SummaryTask{
		TaskNo:         "TST-R13-SCHED",
		SpaceID:        "space1",
		CreatorID:      "creator1",
		SummaryMode:    model.ModeByPerson,
		Status:         model.StatusCompleted,
		TimeRangeStart: now.Add(-time.Hour),
		TimeRangeEnd:   now,
		ScheduleID:     &sched.ID,
	}
	if err := db.Create(&task).Error; err != nil {
		t.Fatalf("create task: %v", err)
	}

	h := NewTaskHandler(db, imDB, "")
	r := setupRound13TaskRouter(h)

	w := doRequest(r, http.MethodGet, fmt.Sprintf("/api/v1/summaries/%d", task.ID), "creator1")
	if w.Code != http.StatusOK {
		t.Fatalf("status=%d body=%s", w.Code, w.Body.String())
	}
	resp := decodeRound13Response(t, w.Body.Bytes())
	data := resp["data"].(map[string]interface{})
	if data["schedule_id"] == nil {
		t.Fatalf("expected inactive schedule_id to be present")
	}
	if int64(data["schedule_id"].(float64)) != sched.ID {
		t.Fatalf("schedule_id=%v want %d", data["schedule_id"], sched.ID)
	}
	if data["schedule_is_active"] == nil || int(data["schedule_is_active"].(float64)) != 0 {
		t.Fatalf("schedule_is_active=%v want 0", data["schedule_is_active"])
	}
}
